import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { loadConfig } from "../shared/config";
import { shadowMatcher, SHELL_TOOLS } from "./shadow";

/**
 * `mduct hook install codex` — the same two hooks and the same catalogue, wired into Codex.
 *
 * Codex's hook contract turns out to be the same one: a JSON payload on stdin with `tool_name`,
 * `tool_input`, `cwd` and `session_id`, and a `hookSpecificOutput` on stdout carrying
 * `permissionDecision` or `additionalContext`. `hook run pre-tool-use` therefore needs no
 * harness-specific code at all — only the registration differs, and Codex keeps everything in one
 * TOML file instead of Claude's two JSON ones.
 */

const START = "# >>> mduct managed — do not edit inside this block >>>";
const END = "# <<< mduct managed <<<";

export function codexConfigPath(): string {
  return process.env.MDUCT_CODEX_CONFIG ?? join(homedir(), ".codex", "config.toml");
}

/** Shell-quote for a TOML basic string. */
const t = (s: string) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

/** The command string Codex should run, resolved the same way the Claude installer resolves it. */
function selfCommand(verb: string): string {
  const entry = process.argv[1] ?? "";
  return entry.startsWith("/$bunfs") || entry === ""
    ? `${process.execPath} ${verb}`
    : `${process.execPath} ${entry} ${verb}`;
}

export function renderBlock(cfg: ReturnType<typeof loadConfig>): string {
  const shadowTools = shadowMatcher(cfg);
  // Codex matchers accept a regex, so the same union works; tool names that do not exist in this
  // harness simply never match, which costs nothing.
  const declared = shadowTools ? shadowTools.split("|") : [];
  const tools = [...new Set([...declared.filter((n) => n !== "Bash"), ...SHELL_TOOLS])].sort();
  const matcher = `mcp__.*|${tools.join("|")}`;

  const catalogued = Object.values(cfg.servers).some((s) => s.mcpCatalog && !s.disabled);
  const lines = [
    START,
    "# Generated by `mduct hook install codex`. Re-run it after changing shadow rules or",
    "# mcpCatalog; remove it with `mduct hook install codex --remove`.",
    "",
    "[[hooks.SessionStart]]",
    "[[hooks.SessionStart.hooks]]",
    `command = ${t(selfCommand("hook run session-start"))}`,
    "",
    "[[hooks.PreToolUse]]",
    `matcher = ${t(matcher)}`,
    "[[hooks.PreToolUse.hooks]]",
    `command = ${t(selfCommand("hook run pre-tool-use"))}`,
  ];
  if (catalogued) {
    const { command, args } = selfExec(["mcp"]);
    lines.push(
      "",
      "# Tool NAMES of catalogued servers, so they sit in the namespace without their schemas.",
      "# Calling one returns the `mduct call …` command; execution stays in the shell.",
      "[mcp_servers.mduct]",
      `command = ${t(command)}`,
      `args = [${args.map(t).join(", ")}]`,
    );
  }
  lines.push(END, "");
  return lines.join("\n");
}

function selfExec(extra: string[]): { command: string; args: string[] } {
  const entry = process.argv[1] ?? "";
  return entry.startsWith("/$bunfs") || entry === ""
    ? { command: process.execPath, args: extra }
    : { command: process.execPath, args: [entry, ...extra] };
}

/** Replace the managed block, or append it. Everything outside the markers is left untouched. */
export function applyBlock(existing: string, block: string | null): string {
  const i = existing.indexOf(START);
  const j = existing.indexOf(END);
  const without = i >= 0 && j > i
    ? (existing.slice(0, i) + existing.slice(j + END.length)).replace(/\n{3,}/g, "\n\n").replace(/^\n+/, "")
    : existing;
  if (block === null) return without;
  const sep = without.length && !without.endsWith("\n\n") ? (without.endsWith("\n") ? "\n" : "\n\n") : "";
  return without + sep + block;
}

/**
 * A key we are about to write must not already exist outside our block — TOML rejects duplicate
 * tables, so Codex would stop loading its whole config and blame itself.
 */
function conflicts(outside: string): string[] {
  const found: string[] = [];
  if (/^\s*\[mcp_servers\.mduct\]/m.test(outside)) found.push("[mcp_servers.mduct]");
  if (/^\s*\[hooks\]/m.test(outside)) found.push("[hooks]");
  return found;
}

export function installCodex(remove: boolean): number {
  const p = codexConfigPath();
  const existing = existsSync(p) ? readFileSync(p, "utf8") : "";

  if (remove) {
    if (!existing.includes(START)) { console.log(`nothing of ours in ${p}`); return 0; }
    write(p, applyBlock(existing, null));
    console.log(`removed from: ${p}`);
    return 0;
  }

  let cfg;
  try { cfg = loadConfig(); } catch (e) {
    console.error(`config unreadable — ${(e as Error).message}`);
    return 1;
  }

  const bad = conflicts(applyBlock(existing, null));
  if (bad.length) {
    console.error(`${p} already defines ${bad.join(" and ")} outside the mduct block.`);
    console.error("TOML rejects duplicate tables, so writing ours would break the whole file. Move or remove it first.");
    return 1;
  }

  write(p, applyBlock(existing, renderBlock(cfg)));
  console.log(`installed into: ${p}`);
  console.log("Hinweis: wirkt ab der nächsten Codex-Session.");
  return 0;
}

function write(p: string, content: string): void {
  mkdirSync(dirname(p), { recursive: true, mode: 0o700 });
  const tmp = `${p}.${process.pid}.tmp`; // atomic: never corrupt someone else's config
  writeFileSync(tmp, content);
  renameSync(tmp, p);
}
