#!/usr/bin/env bun
/**
 * Regenerate the Homebrew formula from a published release.
 *
 *   bun run formula            # current package.json version
 *   bun run formula 0.5.1
 *
 * Reads the checksums from the release assets rather than from dist/, so the formula can only ever
 * describe something that is actually downloadable. A formula built from local files would happily
 * point at a release that was never pushed.
 */
import { $ } from "bun";

const version = (process.argv[2] ?? (await Bun.file("package.json").json()).version).replace(/^v/, "");
const tag = `v${version}`;
const base = `https://github.com/TheFox666/mduct/releases/download/${tag}`;
const targets = [
  { asset: "mduct-darwin-arm64", os: "macos", cpu: "arm" },
  { asset: "mduct-darwin-x64", os: "macos", cpu: "intel" },
  { asset: "mduct-linux-arm64", os: "linux", cpu: "arm" },
  { asset: "mduct-linux-x64", os: "linux", cpu: "intel" },
] as const;

const sha: Record<string, string> = {};
for (const t of targets) {
  const res = await fetch(`${base}/${t.asset}.sha256`);
  if (!res.ok) throw new Error(`${t.asset}.sha256 → HTTP ${res.status}. Is ${tag} published with all four assets?`);
  const s = (await res.text()).trim().split(/\s+/)[0]!;
  if (!/^[0-9a-f]{64}$/.test(s)) throw new Error(`${t.asset}: not a sha256 → "${s}"`);
  sha[t.asset] = s;
}

const block = (cpu: "arm" | "intel", asset: string) => `    on_${cpu} do
      url "${base}/${asset}"
      sha256 "${sha[asset]}"
    end`;

const formula = `# Generated by \`bun run formula\` in TheFox666/mduct — edit there, not here.
class Mduct < Formula
  desc "Every MCP server as a Unix tool: pipe it, script it, run it by hand"
  homepage "https://github.com/TheFox666/mduct"
  version "${version}"
  license "MIT"

  on_macos do
${block("arm", "mduct-darwin-arm64")}
${block("intel", "mduct-darwin-x64")}
  end

  on_linux do
${block("arm", "mduct-linux-arm64")}
${block("intel", "mduct-linux-x64")}
  end

  def install
    bin.install Dir["mduct-*"].first => "mduct"
  end

  def caveats
    <<~EOS
      Point mduct at your MCP servers in ~/.config/mduct/servers.jsonc, or import
      the ones you already have:

        mduct import            # lists servers found in your Claude configs
        mduct import gitlab     # copies one across, moving tokens to the secret store

      For Claude Code, \`mduct hook install claude\` wires up the prompt index and
      the call redirect.
    EOS
  end

  test do
    assert_match "mduct", shell_output("#{bin}/mduct help")
    # a config it cannot load must fail loudly, naming the file — the daemon never starts here
    (testpath/"servers.jsonc").write('{"servers":{"broken":{}}}')
    output = shell_output("MDUCT_CONFIG=#{testpath}/servers.jsonc MDUCT_SOCKET=#{testpath}/s.sock #{bin}/mduct servers 2>&1", 1)
    assert_match "broken", output
  end
end
`;

const out = process.env.MDUCT_TAP ?? `${process.env.HOME}/dev/homebrew-tap`;
const path = `${out}/Formula/mduct.rb`;
await Bun.write(path, formula);
console.log(`${path} → ${version}`);
console.log(`\nnext: cd ${out} && git commit -am "mduct ${version}" && git push`);
try { await $`docker run --rm -v ${out}:/w:ro ruby:3-alpine ruby -c /w/Formula/mduct.rb`.quiet(); console.log("ruby syntax ok"); }
catch { console.log("(no ruby/docker here — syntax unchecked)"); }
